playsound random.glass @a ~~~
damage @e[family=!inanimate,r=0.5] 1 magic entity @r[family=!inanimate,r=15,type=!item,type=!xp_orb,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
execute @r[family=!inanimate,r=4,type=!player,tag=!tamed,type=!xp_orb,type=!item] ~~~ damage @s 1 magic entity @r[family=!inanimate,type=!item,type=!xp_orb,r=15,type=!player,tag=!tamed]
effect @e[family=!inanimate,r=4] slowness 2 4
effect @e[family=!inanimate,r=4] strength 10 1
effect @e[family=!inanimate,r=4] speed 8 2