fill ~ ~.1 ~ ~ ~.1 ~ wheat 7 replace wheat 6
fill ~ ~.1 ~ ~ ~.1 ~ wheat 6 replace wheat 5
fill ~ ~.1 ~ ~ ~.1 ~ wheat 5 replace wheat 4
fill ~ ~.1 ~ ~ ~.1 ~ wheat 4 replace wheat 3
fill ~ ~.1 ~ ~ ~.1 ~ wheat 3 replace wheat 2
fill ~ ~.1 ~ ~ ~.1 ~ wheat 2 replace wheat 1
fill ~ ~.1 ~ ~ ~.1 ~ wheat 1 replace wheat 0
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 7 replace potatoes 6
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 6 replace potatoes 5
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 5 replace potatoes 4
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 4 replace potatoes 3
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 3 replace potatoes 2
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 2 replace potatoes 1
fill ~ ~.1 ~ ~ ~.1 ~ potatoes 1 replace potatoes 0
fill ~ ~.1 ~ ~ ~.1 ~ carrots 7 replace carrots 6
fill ~ ~.1 ~ ~ ~.1 ~ carrots 6 replace carrots 5
fill ~ ~.1 ~ ~ ~.1 ~ carrots 5 replace carrots 4
fill ~ ~.1 ~ ~ ~.1 ~ carrots 4 replace carrots 3
fill ~ ~.1 ~ ~ ~.1 ~ carrots 3 replace carrots 2
fill ~ ~.1 ~ ~ ~.1 ~ carrots 2 replace carrots 1
fill ~ ~.1 ~ ~ ~.1 ~ carrots 1 replace carrots 0
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 7 replace beetroot 6
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 6 replace beetroot 5
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 5 replace beetroot 4
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 4 replace beetroot 3
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 3 replace beetroot 2
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 2 replace beetroot 1
fill ~ ~.1 ~ ~ ~.1 ~ beetroot 1 replace beetroot 0
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 7 replace melon_stem 6
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 6 replace melon_stem 5
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 5 replace melon_stem 4
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 4 replace melon_stem 3
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 3 replace melon_stem 2
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 2 replace melon_stem 1
fill ~ ~.1 ~ ~ ~.1 ~ melon_stem 1 replace melon_stem 0
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 7 replace pumpkin_stem 6
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 6 replace pumpkin_stem 5
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 5 replace pumpkin_stem 4
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 4 replace pumpkin_stem 3
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 3 replace pumpkin_stem 2
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 2 replace pumpkin_stem 1
fill ~ ~.1 ~ ~ ~.1 ~ pumpkin_stem 1 replace pumpkin_stem 0
fill ~ ~-1 ~ ~ ~-1 ~ grass 0 replace dirt 0